# Generated by Django 5.2.12 on 2026-03-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('data_collection', 'Data Collection'), ('identity_check', 'Identity Check'), ('employment_check', 'Employment Check'), ('final_report', 'Final Report')], default='data_collection', max_length=50)),
                ('identity_verified', models.BooleanField(default=False)),
                ('employment_verified', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
