# Generated by Django 5.2.12 on 2026-04-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('identity_check', 'Identity Check'), ('employment_check', 'Employment Check'), ('final_report', 'Final Report')], default='identity_check', max_length=50),
        ),
    ]
