# Generated by Django 5.2.12 on 2026-04-12 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_candidate_completed_at_candidate_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-timestamp']},
        ),
    ]
