# Generated by Django 5.2.12 on 2026-05-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_alter_activitylog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='internal_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
